#!/bin/zsh

# Build the localized version
npm run build:en &&

# Delete all files inside nested repo folder, except its `.git` history
find ../adrianbienias.com/ -mindepth 1 -not -path '../adrianbienias.com/.git*' -not -name 'CNAME' -delete

# Copy all files to the nested repo folder
mv adrianbienias.com-pre/*(D) ../adrianbienias.com/ &&

# Delete empty folder
rm -r adrianbienias.com-pre &&

# Commit changes inside `gh-pages` folder/branch and push them to GitHub
cd ../adrianbienias.com &&
git add . &&
git commit -m 'Automatic deploy' &&
git push
